### ISSUE TITLE
Update run_gmd.sh

### ISSUE THREAD

**Issue by jonesse3** [SeanTBlack/FNLGMD#1]
Got an error: python: can't open file '/source/main.py': [Errno 2] No such file or directory.

Change the CODE variable to:
CODE="main.py"

**Comment by jonesse3** [comment]
Also /ext3/env.sh is an artifact of Singularity and is not recognized by Docker. However, this line does not prevent rest of script to run.

**Comment by SeanTBlack** [comment]
Resolved. Thank you for bringing this to my attention

**Comment by SeanTBlack** [comment]
Resolved. Thank you for bringing this to my attention
